version: '3.4'
services:
  rekor-server-debug:
    build:
      context: .
      target: "debug"
    command: [
      "dlv",
      "exec",
      "--listen=:2345",
      "--headless=true",
      "--log=true",
      "--api-version=2",
      "--",
      "/usr/local/bin/rekor-server",
      "serve",
      "--trillian_log_server.address=trillian-log-server",
      "--trillian_log_server.port=8091",
      "--redis_server.address=redis-server",
      "--redis_server.port=6379",
      "--rekor_server.address=0.0.0.0",
      ]
    restart: always # keep the server running
    ports:
      - "3000:3000"
      - "2345:2345"
    depends_on:
      - mysql
      - redis-server
      - trillian-log-server
