apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
      labels:
        app: redis
        app.kubernetes.io/component: redis
        app.kubernetes.io/instance: redis
        app.openshift.io/runtime-version: 5.0.10
      name: redis
    spec:
      ports:
        - name: 6379-tcp
          port: 6379
          protocol: TCP
          targetPort: 6379
      selector:
        app: redis
        deploymentconfig: redis
      sessionAffinity: None
      type: ClusterIP
    status:
      loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
