apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
      labels:
        app: rekor-server
        app.kubernetes.io/component: rekor-server
        app.kubernetes.io/instance: rekor-server
        app.openshift.io/runtime-version: "0.1"
      name: rekor-server
    spec:
      ports:
        - name: 3000-tcp
          port: 3000
          protocol: TCP
          targetPort: 3000
      selector:
        app: rekor-server
        deploymentconfig: rekor-server
      sessionAffinity: None
      type: ClusterIP
    status:
      loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
